// <auto-generated />
using Backloggd.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backloggd.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260614165816_BildHinzugefuegt")]
    partial class BildHinzugefuegt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("HauserKarlHeinz_3CK")
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backloggd.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpielId")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReviewId");

                    b.HasIndex("SpielId");

                    b.ToTable("Review", "HauserKarlHeinz_3CK");
                });

            modelBuilder.Entity("Backloggd.Models.Spiel", b =>
                {
                    b.Property<int>("SpielId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpielId"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Bild")
                        .HasColumnType("bytea");

                    b.Property<decimal>("DurchschnittsBewertung")
                        .HasColumnType("numeric");

                    b.Property<string>("Entwickler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Release")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpielId");

                    b.ToTable("Spiel", "HauserKarlHeinz_3CK");
                });

            modelBuilder.Entity("Backloggd.Models.Review", b =>
                {
                    b.HasOne("Backloggd.Models.Spiel", "Spiel")
                        .WithMany("ReviewsDesSpiels")
                        .HasForeignKey("SpielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spiel");
                });

            modelBuilder.Entity("Backloggd.Models.Spiel", b =>
                {
                    b.Navigation("ReviewsDesSpiels");
                });
#pragma warning restore 612, 618
        }
    }
}
